- name: Install Openshift Python Library
  command: pip3 install openshift

- name: Install Ansible Galaxy Kubernetes
  command: ansible-galaxy collection install community.kubernetes

- name: Install Stable repos
  community.kubernetes.helm_repository:
    name: fluent
    repo_url: "https://fluent.github.io/helm-charts"

- name: Update helm repos
  command: helm repo update
  delegate_to: localhost

- name: Create namespace
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: Apply Fluent-Bit
  kubernetes.core.helm:
    name: "{{ deployment }}"
    chart_ref: fluent/fluent-bit
    release_namespace: "{{ namespace }}"
    release_values:
      config:
        inputs: "{{ inputs }}"
        customParsers: "{{ customParsers }}"
        outputs: "{{ outputs }}"
        filters: "{{ filters }}"
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

