- name: Install Openshift Python Library
  command: pip3 install openshift

- name: Install Ansible Galaxy Kubernetes
  command: ansible-galaxy collection install community.kubernetes

- name: Install Stable repos
  community.kubernetes.helm_repository:
    name: stable
    repo_url: "https://charts.helm.sh/stable"

- name: Update helm repos
  command: helm repo update
  delegate_to: localhost

- name: Create namespace
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: Apply Fluent-Bit
  kubernetes.core.helm:
    name: "{{ deployment }}"
    chart_ref: stable/fluent-bit
    release_namespace: "{{ namespace }}"
    release_values:
      image:
        tag: 1.6.2
      testFramework:
        enabled: false
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/path: "/api/v1/metrics/prometheus"
            prometheus.io/port: "2020"
            prometheus.io/scrape: "true"
        serviceMonitor:
          enabled: true
          additionalLabels:
            namespace: "{{ namespace }}"
            interval: 30s
            scrapeTimeout: 10s
      backend:
        type: es
        es:
          host: elasticsearch-master
          http_user: "{{ elasticsearchuser }}"
          http_passwd: "{{ elasticsearchpassword }}"
          tls_verify: "off"
      parsers:
        enabled: true
        regex: "{{ parsers }}"
        json: "{{ json }}"
      extraEntries:
        input: "{{ input }}"
