- name: Initialize Kubernetes Control Plane
  hosts: controlplane
  vars_files:
    - files/fluent-bit-vault.yaml
  vars:
    namespace: monitoring

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift

    - name: Install Ansible
      become: true
      apt:
        name: ansible
        state: present
        update_cache: yes

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes

    - name: Create monitoring namespace
      community.kubernetes.k8s:
        name: '{{ namespace }}'
        api_version: v1
        kind: namespace
        state: present

    - name: Copy Helm Charts
      copy:
        src: ../fluent-bit
        dest: /tmp/

    - name: Copy Customization
      copy:
        src: ../fluent-bit-values.yaml
        dest: /tmp/

    - name: Apply Fluent-bit chart
      command: >
        helm install fluent-bit -n '{{ namespace }}' /tmp/fluent-bit -f /tmp/fluent-bit-values.yaml
        --set backend.es.http_passwd='{{ elasticsearchpassword }}'
        --set backend.es.http_user='{{ elasticsearchuser }}'

