namespace: monitoring

deployment: fluent-bit

customParsers: |
  [PARSER]
      Name        docker
      Format      json
      Time_Keep   On
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L

  [PARSER]
      Name        jenkins
      Format      regex
      Regex       ^(?<time>.*[^\[])\s+\[id=(?<id>\d+)\]\s+(?<level>\w+)\s+(?<message>.*)$
      Time_Key    time
      Time_Format %Y-%m-%d %H:%M:%S.%L

  [PARSER]
      Name        nextcloud
      Format      regex
      Regex       ^(?<remote>[^ ]*)\s+-\s+-\s+\[(?<time>[^\]]*)\]\s+\\"(?<method>\S+)\s+(?<path>[^\ ]*?)\s+(?<protocol>\S+[^\\])\\"\s+(?<status>\d+)\s+(?<length>\d+)\s+\\"-\\"\s+\\"(?<operation>.+[^\\"])\\".*$
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z

  [PARSER]
      Name        sonarqube
      Format      regex
      Regex       ^(?<time>[\d|\.|\s|:]+) (?<level>\w+)\s+(?<logType>\S+)\[(?<uid>\S+[^\]])]\[(?<message>\S+[^\]])]\s+(?<task>.*[^\|])\|\s+project=(?<project>.*[^\|])\|\s+type=(?<type>\w+[^\|])\|\s+id=(?<id>\S+[^\|])\|\s+submitter=(?<submitter>\S+[^\|])\|\s+status=(?<status>.*[^\|])\|\s+time=(?<duration>\d+ms).*$
      Time_Key    time
      Time_Format %Y.%m.%d %H:%M:%S

  [PARSER]
      Name        apache
      Format      regex
      Regex       ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z

  [PARSER]
      Name        apache2
      Format      regex
      Regex       ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z

  [PARSER]
      Name        apache_error
      Format      regex
      Regex       ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z

  [PARSER]
      Name        nginx
      Format      regex
      Regex       ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z

  [PARSER]
      Name        selenium
      Format      regex
      Regex       ^(?<time>[\d|\.|\s|:]+) (?<level>\w+[^\[])\s+\[(?<type>.*[^\]])]\s+-\s+(?<message>.*)
      Time_Key    time
      Time_Format %H:%M:%S.%z

  [PARSER]
      Name        syslog
      Format      regex
      Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
      Time_Key    time
      Time_Format %b %d %H:%M:%S

  [PARSER]
      Name        json
      Format      json
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z


inputs: |
  [INPUT]
      Name tail
      Path /var/log/containers/*.log
      multiline.parser docker, cri
      Tag kube.*
      Mem_Buf_Limit 5MB
      Skip_Long_Lines On

  [INPUT]
      Name systemd
      Tag host.*
      Systemd_Filter _SYSTEMD_UNIT=kubelet.service
      Read_From_Tail On

  [INPUT]
      name cpu
      tag  cpu.local
      interval_sec 30

  [INPUT]
      name mem
      tag mem.local
      interval_sec 30

  [INPUT]
      name tail
      path /var/log/syslog
      tag logs.local

filters: |
  [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On

  [FILTER]
      name modify
      match cpu*
      Remove_regex cpu\d+.*
      Add hostname ${MY_NODE_NAME}

  [FILTER]
      name modify
      match mem*
      Add hostname ${MY_NODE_NAME}

  [FILTER]
      name modify
      match logs*
      Add hostname ${MY_NODE_NAME}

outputs: |
  [OUTPUT]
      Name es
      Match kube.*
      Host elasticsearch-master
      Logstash_Format On
      Retry_Limit False
      Type  flb_type
      Time_Key @timestamp
      Replace_Dots On
      Logstash_Prefix kubernetes_cluster
      HTTP_User "{{ elasticsearchuser }}"
      HTTP_Passwd "{{ elasticsearchpassword }}"

  [OUTPUT]
      Name es
      Match cpu.*
      Host elasticsearch-master
      Logstash_Format On
      Retry_Limit False
      Type  flb_type
      Time_Key @timestamp
      Replace_Dots On
      Logstash_Prefix cpu
      HTTP_User "{{ elasticsearchuser }}"
      HTTP_Passwd "{{ elasticsearchpassword }}"

  [OUTPUT]
      Name es
      Match mem.*
      Host elasticsearch-master
      Logstash_Format On
      Retry_Limit False
      Type  flb_type
      Time_Key @timestamp
      Replace_Dots On
      Logstash_Prefix cpu
      HTTP_User "{{ elasticsearchuser }}"
      HTTP_Passwd "{{ elasticsearchpassword }}"

  [OUTPUT]
      Name es
      Match log.*
      Host elasticsearch-master
      Logstash_Format On
      Retry_Limit False
      Type  flb_type
      Time_Key @timestamp
      Replace_Dots On
      Logstash_Prefix cpu
      HTTP_User "{{ elasticsearchuser }}"
      HTTP_Passwd "{{ elasticsearchpassword }}"

elasticsearchuser: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61636130613662613635366162376631363037303066333266303731633265303932666365393639
  3238623263363732626365326466626534666634363261640a663865636230393933386530306537
  31313739373833353761626663326534343065356337306361346535386433646232343161326639
  3539346434646530620a366661366561323734336366383131373464323834386333326438666530
  3864
elasticsearchpassword: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30383930373834616635623630363231393463346235613062373061366438326165336536653766
  6562343332653837323966643966393034653363353166300a666434386464633365626331663034
  38626136363134363436373861326637633638303764343963363639393836383761346631323431
  3835653465316234610a626231666564313337663136376531343534363263623032363561633033
  6536
